//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAp_MVC_L46_EF_52323
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_L46_MVC_EF_52323Entities1 : DbContext
    {
        public DB_L46_MVC_EF_52323Entities1()
            : base("name=DB_L46_MVC_EF_52323Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
    
        public virtual ObjectResult<sp_tblEmployee_get_Result> sp_tblEmployee_get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblEmployee_get_Result>("sp_tblEmployee_get");
        }
    
        public virtual int sp_tblEmployee_insert(string name, string city, Nullable<int> age)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblEmployee_insert", nameParameter, cityParameter, ageParameter);
        }
    }
}
