//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAp_MVC_L46_EF_52323
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee// table class not a table
    {
        public int empid { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public Nullable<int> age { get; set; }
    }
}
